name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment with the highest LTS version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use the highest available LTS version
          cache: 'pnpm'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: |
          corepack enable # Ensures pnpm is installed with Node.js
          pnpm --version # Verifies pnpm is installed and available in PATH

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run tests
      - name: Run tests
        run: pnpm test

      # Step 6: Run Chromatic
      - name: Run Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} # Set this secret in your repository settings
        run: |
          pnpm dlx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}